name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build_type:
        type: string
        default: DEBUG
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
