name: Pull Request Labeler

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/labeler@v5
        #      - uses: kyle-singer/superbrothers-close-pull-request@v3
        #        with:
        #          comment: "Hi! We aren't accepting updates to workflow files in pull requests, so must reject this pull request."
